### ISSUE TITLE
Progressive Web App checklist

### ISSUE THREAD

**Issue by CrazyStevenz** [college-resources/web#46]
Complete the PWA checklist:

- [x] [Current page does not respond with a 200 when offline](https://web.dev/works-offline/)

- [x] [start_url does not respond with a 200 when offline](https://web.dev/offline-start-url)

- [x] [Does not register a service worker that controls page and start_url](https://web.dev/service-worker)

- [x] [Is not configured for a custom splash screen](https://web.dev/splash-screen)

- [x] [Manifest doesn't have a maskable icon](https://web.dev/maskable-icon-audit)

- [ ] [Additional items to manually check](https://web.dev/pwa-checklist)

**Comment by CrazyStevenz** [comment]
Last task is tracked here #52.
