### ISSUE TITLE
Optimal Progressive Web App checklist

### ISSUE THREAD

**Issue by FeedMyCat54** [college-resources/web#52]
- [ ] Provides a custom offline page

- [ ] Provides an offline experience

- [ ] Is fully accessible

- [ ] Can be discovered through search

- [ ] Works with any input type

- [ ] Provides context for permission requests

- [ ] Follows best practices for healthy code

https://web.dev/pwa-checklist/#optimal
